In [3]:
import numpy as np
import math
file = open("bfsdata.txt", "r")

In [4]:
#read the first line to get the vertex count :-
line1 = file.readline().strip()
vertex_count = int(line1) + 1

In [5]:
#create an adjacency matrix
adj_matrix = np.zeros((vertex_count, vertex_count), dtype='int')
print(adj_matrix)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [7]:
while True:
    line = file.readline().strip()
    if not line:
        break
    vertices = line.split(' ')
    u = int(vertices[0])
    v = int(vertices[1])
    adj_matrix[u][v] = 1
print(adj_matrix)

[[0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0]
 [0 1 0 0 1 1 0]
 [0 1 0 0 0 1 0]
 [0 0 1 0 0 1 1]
 [0 0 1 1 1 0 1]
 [0 0 0 0 1 1 0]]


In [11]:
color = np.empty(vertex_count, dtype = 'object')
color[:] = 'WHITE'

In [12]:
parent = np.empty(vertex_count, dtype = 'object')
parent[:] = np.NaN

In [13]:
d = np.zeros(vertex_count, dtype = 'int')
d[:] = math.inf

In [15]:
from queue import Queue

my_queue = Queue(maxsize = vertex_count)

In [16]:
def bfs(s):
    color[s] = 'GRAY'
    parent[s] = np.NaN
    d[s] = 0
    my_queue.put(s)
    while not my_queue.empty():
        u = my_queue.get()
        for v in range(1, vertex_count):
            if adj_matrix[u][v] == 1:
                if color[v] == 'WHITE':
                    color[v] = 'GRAY'
                    d[v] = d[u] + 1
                    parent[v] = u
                    my_queue.put(v)
        color[u] = 'BLACK'
        print(str(u) + ' distance ' + str(d[u]))
    return

bfs(1)

1 distance 0
2 distance 1
3 distance 1
4 distance 2
5 distance 2
6 distance 3
